### ISSUE TITLE
Cannot login with new account

### ISSUE THREAD

**Issue by tillwenke** [flov/hitchlog-nextjs#11]
Getting 
```Application error: a client-side exception has occurred (see the browser console for more information).```
on mobile and laptop. Firefox and Chrome.

**Comment by tillwenke** [comment]
![Screenshot from 2023-12-10 18-08-44](https://github.com/flov/hitchlog-nextjs/assets/38500891/17516337-2fc9-44ed-9197-2d3cdc06b6b2)

**Comment by flov** [comment]
I fixed the issue. Can you please try again?
