### ISSUE TITLE
RFE - R(equest) F(or) E(nhancement) - provide an option to somehow merge trips or allow for round-trips

### ISSUE THREAD

**Issue by prino** [flov/hitchlog-nextjs#4]
My first trip in 1980 went from De Bilt (NL) to De Bilt, via Stockholm. I can split it into multiple parts, and see [Rides per trip dropdown needs to allow for more trips](https://github.com/flov/hitchlog-nextjs/issues/3) that would my now 303 trips turn into 334 trips, as I've got two trips with over 90 rides, one with 67, 33 with between 31 and 58 rides, and the remaining 267 with less than 30 rides each. 

Anyway, splitting most of my trips is required anyway, as most of them are A-to-A round-trips, via B,C,D,E,etc, so an option to add, not sure how many intermediate stops Google allows nowadays, the maximum number of intermediate stops.

**Comment by flov** [comment]
I would suggest splitting those trips into several.
