### ISSUE TITLE
Can edit my profile, but going to profile gives a 404

### ISSUE THREAD

**Issue by prino** [flov/hitchlog-nextjs#9]
The title says it all, I'm there, but I'm not.

**Comment by AugustasV** [comment]
Same

**Comment by flov** [comment]
Hi! Thanks for your messages. The server went down while I was away on
holidays, I just fixed it. Sorry about that :/

**Comment by flov** [comment]
sorry guys, something is seriously wrong with the server. I can't figure it
out now because I'm on holiday unfortunately. I will have a look next week.
